### ISSUE TITLE
Add prebuilt Linux kernel and rootfs images

### ISSUE THREAD

**Issue by ChinYikMing** [sysprog21/rv32emu-prebuilt#2]
The Linux kernel and rootfs images should be stored in this repository to minimize the size of the rv32emu repository and improve its clone speed. These images will be prefetched when users want to run system emulation.

Todo:
1. Calculate the SHA-1 of the Linux kernel and rootfs images and save the hashes in `sha1sum-riscv32` (or preferably `sha1sum-system`).
2. Tweak the `artifact` target in rv32emu to reflect the changes.

**Comment by ChinYikMing** [comment]
Cc. @vacantron , If you're ready, I can submit a pull request to upload the Linux kernel and rootfs images, and I'll need your assistance with the first task on the todo list. Thanks!

**Comment by vacantron** [comment]
> Cc. @vacantron , If you're ready, I can submit a pull request to upload the Linux kernel and rootfs images, and I'll need your assistance with the first task on the todo list. Thanks!

Sure! But the binaries are built and uploaded from the CI in the `rv32emu` repository. I think you could test the CI in your fork and create another pull request to `rv32emu`.

**Comment by ChinYikMing** [comment]
> > Cc. @vacantron , If you're ready, I can submit a pull request to upload the Linux kernel and rootfs images, and I'll need your assistance with the first task on the todo list. Thanks!
> 
> Sure! But the binaries are built and uploaded from the CI in the `rv32emu` repository. I think you could test the CI in your fork and create another pull request to `rv32emu`.

```
- name: Test file change
        id: test-file-change
        uses: tj-actions/changed-files@v45
        with:
          fetch_additional_submodule_history: 'true'
          files: |
            mk/artifact.mk
            tests/ansibench/**
            tests/rv8-bench/**
            tests/doom/**
            tests/quake/**
            tests/scimark2/**
            tests/*.c
```

Does the workflow in GitHub only trigger when these files change during the artifact build process? If so, shall we create a submodule for system artifacts?

**Comment by vacantron** [comment]
> Does the workflow in GitHub only trigger when these files change during the artifact build process? If so, shall we create a submodule for system artifacts?

Yes, you can add a submodule for building kernel image, or any file you need (make sure the additional files are added to the `files` field in yaml).

**Comment by ChinYikMing** [comment]
> > Does the workflow in GitHub only trigger when these files change during the artifact build process? If so, shall we create a submodule for system artifacts?
> 
> Yes, you can add a submodule for building kernel image, or any file you need (make sure the additional files are added to the `files` field in yaml).

Opening a new repository to store these is too resource-intensive, so I proposed storing only their version file in rv32emu instead.

**Comment by ChinYikMing** [comment]
Could you clarify if I should precalculate and upload the SHA value of the Linux images first, so that `ENABLE_PREBUILT=0` in rv32emu can pull the SHA file for comparison? Or would an empty SHA file in this repository also work?

**Comment by ChinYikMing** [comment]
I have to separate the release tag for Linux image and test bench ELF executables respectively in [commit](https://github.com/sysprog21/rv32emu/pull/508/commits/3432824064c9d1cd3ad45bbb041a6999b49413c2), can you check if it is feasible? If nothing is concerned, I will try to update the tag of the latest release in this repo (by adding a suffix '-ELF') to pass CI in rv32emu. Thanks!

**Comment by jserv** [comment]
> I have to separate the release tag for Linux image and test bench ELF executables respectively in [commit](https://github.com/sysprog21/rv32emu/pull/508/commits/3432824064c9d1cd3ad45bbb041a6999b49413c2), can you check if it is feasible?

Put the versioning information within a single file. See https://github.com/sysprog21/kvm-host/blob/master/mk/external.mk

**Comment by ChinYikMing** [comment]
> > I have to separate the release tag for Linux image and test bench ELF executables respectively in [commit](https://github.com/sysprog21/rv32emu/pull/508/commits/3432824064c9d1cd3ad45bbb041a6999b49413c2), can you check if it is feasible?
> 
> Put the versioning information within a single file. See https://github.com/sysprog21/kvm-host/blob/master/mk/external.mk

I’m concerned that refining the single file could still trigger a rebuild, even if the changes don’t involve version bumping. However, it’s possible to make this work by checking the difference  and only triggering the rebuild if the changes specifically relate to version bumping.
